### ISSUE TITLE
error when running Dotdigitalgroup\Email\Model\Cron::contactSync

### ISSUE THREAD

**Issue by gingerben** [dotmailer/dotmailer-magento2-extension-enterprise#18]
we upgraded to 4.3.2 of the dotmailer/dotmailer-magento2-extension (basically and hour before 4.3.3)  and since then have been getting the following error on the above cron 

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Dotdigitalgroup\Enterprise\Plugin\CustomerPlugin::beforeSetContactData(), 1 passed in /data/webroot/mag2.paulsmith.com/20200130_092012/vendor/magento/framework/Interception/Interceptor.php on line 121 and exactly 2 expected in /data/webroot/mag2.paulsmith.com/20200130_092012/vendor/dotmailer/dotmailer-magento2-extension-enterprise/Plugin/CustomerPlugin.php:74
Stack trace:
#0 /data/webroot/mag2.paulsmith.com/20200130_092012/vendor/magento/framework/Interception/Interceptor.php(121): Dotdigitalgroup\Enterprise\Plugin\CustomerPlugin->beforeSetContactData(Object(Dotdigitalgroup\Email\Model\Apiconnector\Customer\Interceptor))
#1 /data/webroot/mag2.paulsmith.com/20200130_092012/vendor/magento/framework/Interception/Interceptor.php(153): Dotdigitalgroup\Email\Model\Apiconnector\Customer\Interceptor->Magento\Framework\Interception\{closure}()
#2 /data/webroot/mag2.paulsmith.com/20200130_092012/generated/code/Dotdigitalgroup/Email/Model/Apiconnector/Customer/I in /data/webroot/mag2.paulsmith.com/20200130_092012/vendor/dotmailer/dotmailer-magento2-extension-enterprise/Plugin/CustomerPlugin.php on line 74

**Comment by benathomeofchampions** [comment]
Hi Ben,
Sorry you have had this issue.

We have made some changes in 4.3.1 that affect our Enterprise module as well. You will need to upgrade to 1.0.5 of the Enterprise module to resolve this.

`composer require dotmailer/dotmailer-magento2-extension-enterprise:"1.0.5"`

**Comment by gingerben** [comment]
Hi Ben

I am still having an issue after upgrading to 1.0.5 with dotmailer 4.3.3 (error at the bottom)

the issue is
$this->helper->getEnterpriseAttributes($customerDataFieldProvider->getWebsite())
Is returning null so having
 
$result += $this->helper->getEnterpriseAttributes($customerDataFieldProvider->getWebsite())
Causes the issue
 
As a temp fix I have put an if to check if $this->helper->getEnterpriseAttributes($customerDataFieldProvider->getWebsite())
Is set, if not just return $result

thanks

PHP Fatal error:  Uncaught Error: Unsupported operand types in /data/webroot/mag2.paulsmith.com/20200205_171530/vendor/dotmailer/dotmailer-magento2-extension-enterprise/Plugin/CustomerDataFieldProviderPlugin.php:39
Stack trace:
#0 /data/webroot/mag2.paulsmith.com/20200205_171530/vendor/magento/framework/Interception/Interceptor.php(146): Dotdigitalgroup\Enterprise\Plugin\CustomerDataFieldProviderPlugin->afterGetAdditionalDataFields(Object(Dotdigitalgroup\Email\Model\Apiconnector\CustomerDataFieldProvider\Interceptor), Array)
#1 /data/webroot/mag2.paulsmith.com/20200205_171530/vendor/magento/framework/Interception/Interceptor.php(153): Dotdigitalgroup\Email\Model\Apiconnector\CustomerDataFieldProvider\Interceptor->Magento\Framework\Interception\{closure}()
#2 /data/webroot/mag2.paulsmith.com/20200205_171530/generated/code/Dotdigitalgroup/Email/Model/Apiconnector/CustomerDataFieldProvider/Interceptor.php(26): Dotdigitalgroup\Email\Model\Apiconnector\CustomerDataFieldProvider\Interceptor->___callPlugins('getAdditionalDa...', Arra in /data/webroot/mag2.paulsmith.com/20200205_171530/vendor/dotmailer/dotmailer-magento2-extension-enterprise/Plugin/CustomerDataFieldProviderPlugin.php on line 39

**Comment by benathomeofchampions** [comment]
Hi Ben,
Yes, that one has also appeared on our radar, too - I'm very sorry for the continued problems you're having. 

We have a fix coming, although this problem can be resolved by running our 'Automap Datafields' function.

This can either be done via the admin: `Stores > Configuration > Dotdigital > Developer > Automap Data Fields`

Or the cli: `bin/magento dotdigital:dotdigital:connector:automap`

Running the sync after this should work correctly.

**Comment by gingerben** [comment]
Hi Ben

Cheers I have run that, I am still going to leave the check to make sure it is set for now then I know it will not fail.
